# Generated by Django 4.1 on 2022-08-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=240)),
                ('venue', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=240)),
                ('state', models.CharField(max_length=240)),
                ('country', models.CharField(max_length=240)),
                ('date', models.DateTimeField()),
                ('genre', models.CharField(max_length=240)),
            ],
        ),
    ]
