# Generated by Django 4.1 on 2022-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertlistings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploaded_images/'),
        ),
    ]
