# Generated by Django 4.1 on 2022-08-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertlistings', '0002_concert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='shortDate',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
