version: "3.8"

services:

  db:
    restart: always
    image: postgres
    container_name: concerts-postgres
    environment:
      - POSTGRES_USER=ncolosso
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=concerts
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
